find_path(GLOG_INCLUDE_PATH glog/logging.h)
find_library(GLOG_LIBRARY NAMES glog)
if (NOT GLOG_INCLUDE_PATH)
    message(FATAL_ERROR "Fail to find glog header")
endif ()
if (NOT GLOG_LIBRARY)
    message(FATAL_ERROR "Fail to find glog lib")
endif ()
include_directories(${GLOG_INCLUDE_PATH})